"""add_index_to_portfolio_user_id

Revision ID: 57a934a58ff6
Revises: 46d87317d8b4
Create Date: 2026-04-02 11:19:16.702877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a934a58ff6'
down_revision: Union[str, Sequence[str], None] = '46d87317d8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    # ### end Alembic commands ###
