name: Python Automation
on: [push]

jobs:
  check-my-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest pytest-asyncio fastapi httpx sqlalchemy alembic psycopg2-binary

      - name: Run Tests
        run: pytest